### ISSUE TITLE
Unable to sign out with Facebook

### ISSUE THREAD

**Issue by GuillaumeVT** [sabyasachibiswal/angular5-social-login#10]
Hi,

First thanks for this great package!

I added both Google and Facebook logins.
With Google I'm able to sign in/out.
I can also sign in with Facebook but whenever I call the sign out service I get the following error:
Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'deny'.

Has anyone encountered this and would know how to get the Facebook logout working?

Thanks,
Guillaume

**Comment by vicabelotelova** [comment]
@GuillaumeVT  How are you fixed it?

**Comment by GuillaumeVT** [comment]
Hi! I actually didn't fix it.

I can logout normally in production but on my localhost, I never managed to
do it.
