### ISSUE TITLE
No Provider for AuthServiceConfig

### ISSUE THREAD

**Issue by sqlsolver** [sabyasachibiswal/angular5-social-login#2]
In Chrome Console:
````
core.js:1427 ERROR Error: Uncaught (in promise): Error: StaticInjectorError[AuthServiceConfig]: 
  StaticInjectorError[AuthServiceConfig]: 
    NullInjectorError: No provider for AuthServiceConfig!
Error: StaticInjectorError[AuthServiceConfig]: 
  StaticInjectorError[AuthServiceConfig]: 
    NullInjectorError: No provider for AuthServiceConfig!
````
after following tutorial. You are added as a collaborator on the [repo](https://github.com/sqlsolver/ebspug/issues/1) if you want to test example.

**Comment by softspoiler** [comment]
@sqlsolver Did you added the **AuthServiceConfig** to providers in your main module?
`providers: [
    {
      provide: AuthServiceConfig,
      useFactory: getAuthServiceConfigs
    }
  ],`

**Comment by sabyasachibiswal** [comment]
@softspoiler Thanks
