### ISSUE TITLE
calling signout does nothing :-(

### ISSUE THREAD

**Issue by jegjessing** [sabyasachibiswal/angular5-social-login#31]
All values are still saved and I'm not asked to choose account after executing signout

**Comment by sebastiangug** [comment]
@jegjessing  have you found a solution to this?

**Comment by jegjessing** [comment]
Nope, gave up and are currently not using it

**Comment by sebastiangug** [comment]
It's generally not a big issue regarding implementation -- it's just that whoever made this package hasn't given anyone the possibility of adjusting any kind of settings at all. 

All you have to do is add a url parameter to prompt consent...  I think I'll fork it later and add that possibility.

**Comment by sammysium** [comment]
@michaelbats any update on that please? I am stuck as i cant sign out

**Comment by sebastiangug** [comment]
@sammysium we have to stop using half-assed packages that have no chance of doing what they promise, I think it's best you implement each social login separately using the official SDK, both google and microsoft ones are straightforward to use and have types for everything, so using it with typescript will be a breeze.
