### ISSUE TITLE
Angular - Cannot find module 'rxjs'.

### ISSUE THREAD

**Issue by rms095** [sabyasachibiswal/angular5-social-login#41]
Hi Team,

I created new project and followed the steps which is mentioned on the npm page 
but still I am getting below errors.
ERROR in ../node_modules/angular-6-social-login/auth.service.d.ts(1,28): error TS2307: Cannot find module 'rxjs'
What I tried :
1. remove node_modules and npm install - same error
2. verify "moduleResolution": "node" in tsconfig.json

any comment??

Versions :
Node - v8.11.3
CLI - 7.2.3
![image](https://user-images.githubusercontent.com/6409315/56147935-e1533200-5fc6-11e9-8157-bf3a64b431b1.png)

**Comment by sabyasachibiswal** [comment]
https://stackoverflow.com/questions/50341119/cannot-find-module-angular-core-cannot-find-module-rxjs
