### ISSUE TITLE
Declaration or statement expected.

### ISSUE THREAD

**Issue by abhisheksharma662** [sabyasachibiswal/angular5-social-login#42]
export function getAuthServiceConfigs() {
  let config = new AuthServiceConfig(
      [
        {
          id: GoogleLoginProvider.PROVIDER_ID,
          provider: new GoogleLoginProvider("476522047024-sdu9l9cav23g7cs6g2lhm4nc89h6boje.apps.googleusercontent.com")
        }
      ];
  );
  return config;
}

code is completely fine but throwing error and not able to run properly can anyone give me solutiuon ?

**Comment by abhisheksharma662** [comment]
i am searching from past 1 weak to sort out the issue and not found anything can anyone please solve my problem so that i can use this plugin and suggest everyone to use it

**Comment by sabyasachibiswal** [comment]
Can you provide with the error it's throwing?

**Comment by abhisheksharma662** [comment]
https://ibb.co/0MX3Chc
https://ibb.co/8Kk9j7D

sir 2 jpg i marked one is my terminal jpg second one is my code jpg 
as you can see terminal is throwing error on line no 83 Declaration or statement expected

**Comment by sabyasachibiswal** [comment]
@abhisheksharma662 I guess you are using angular6-social-login. 
You can connect me : live:224d392db8c54072(skype)

**Comment by sabyasachibiswal** [comment]
```
import {AuthServiceConfig, GoogleLoginProvider, SocialLoginModule} from 'angular5-social-login';
import {environment} from '../environments/environment';

export function getAuthServiceConfigs() {
  let config = new AuthServiceConfig([{
        id: GoogleLoginProvider.PROVIDER_ID,
        provider: new GoogleLoginProvider(environment.GOOGLE_SITE_KEY)
  }]);
  return config;
}
```

This will resolve the issue.
