### ISSUE TITLE
email as undefined in my response

### ISSUE THREAD

**Issue by ghost** [sabyasachibiswal/angular5-social-login#5]
when i login by using mobile number,my email is undefined. also i want to extra details like gender,mobile number how can i get those fields in response

**Comment by Tzeny** [comment]
I have this problem too; I tried using Edge and it worked fine.

**Comment by Tzeny** [comment]
For me it was caused by an extension of Chrome

**Comment by lashisu** [comment]
I am still getting this issue. It is only for my profile. Other user can login and get email. No idea, how to fix this? I have checked over multiple browsers. But no luck...,
