### ISSUE TITLE
Cannot request custom fields for Facebook Auth

### ISSUE THREAD

**Issue by ronnykwon** [sabyasachibiswal/angular5-social-login#7]
Cannot customize the requested field from Facebook.
I would like to retrieve the birthday, gender and other fields but for now it seems that it's limited to name, email

**Comment by stevemurch** [comment]
By default, Facebook limits what you can get with the default permissions. You'll need to customize the FB.Login call that you can find in the angular5-social-login.umd.js file. In the case of birthday, for instance, you'll need to add user_birthday to the list of scope CSV items, and then add "birthday" to the list of /me GET requests. Note that as of this writing, the SDK that this particular angular component uses is a few versions old, and you'll have to submit your FB app for review before login is shown without warning.

**Comment by sabyasachibiswal** [comment]
Thanks @stevemurch
